name: Build GNU/Linux
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            packages: 'gcc-10 g++-10'
            env_cc: gcc-10
            env_cxx: g++-10
          - os: ubuntu-latest
            packages: 'gcc-14 g++-14'
            env_cc: gcc-14
            env_cxx: g++-14

    env:
      CC: ${{ matrix.env_cc }}
      CXX: ${{ matrix.env_cxx }}

    name: ${{ matrix.os }} - ${{ matrix.packages }}

    steps:
      - uses: actions/checkout@v6
      - name: install build dependencies
        run: sudo apt install -y meson nasm ${{ matrix.packages }}
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
